// src/components/dishesData.js

const dishesData = [
    {
      id: 1,
      name: 'Beef Empanadas',
      description: 'Delicious empanadas with beef filling.',
      price: 6.0,
      image: '/images/beef-empanadas.jpg',
      category: 'Appetizers',
    },
    {
      id: 2,
      name: 'Chicken Empanadas',
      description: 'Tasty chicken empanadas.',
      price: 6.0,
      image: '/images/chicken-empanadas.jpg',
      category: 'Appetizers',
    },
    {
      id: 3,
      name: 'Grilled Salmon',
      description: 'Fresh salmon fillet grilled to perfection.',
      price: 15.0,
      image: '/images/grilled-salmon.jpg',
      category: 'Main Courses',
    },
    {
        id: 4,
        name: 'x2 Vegan Empanadas',
        description: "Side of 2oz 'aji' sauce: Finely chopped onions, coriander lime juice, oil a bit of vinegar then blended chillis.",
        price: 6.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Appetizers',
        glutenFree: true,
        vegan: true,
    },
    {
        id: 5,
        name: 'BBQ Pork Fries',
        description: "Cheese fries topped with BBQ pulled pork cooked in sofrito sauce.",
        price: 13.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Loaded Fries',
        glutenFree: true,
    },
    {
        id: 6,
        name: 'Chicken Session Fries (GF) (Halal)',
        description: "Cheese fries topped with pulled chicken breast, sofrito sauce and thousand island sauce on the side.",
        price: 13.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Loaded Fries',
        glutenFree: true,
        halal: true,
        popular: true,
    },
    {
        id: 7,
        name: 'Salchipapas',
        description: "Cheese fries topped with hot dog sausages, bacon, crispy onions and thousand island sauce on the side.",
        price: 13.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Loaded Fries',
    },
    {
        id: 8,
        name: 'Vegetarian Dirty Fries',
        description: "Cheese fries topped with grilled sweet corn, red onions and jalapeños. Thousands island sauce on the side.",
        price: 12.5,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Loaded Fries',
        vegetarian: true,
    },
    {
        id: 9,
        name: 'Cheesy Arepa',
        description: "Circular grilled cheese in a traditional cornmeal dough (GF).",
        price: 5.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Starters',
        glutenFree: true,
    },
    {
        id: 10,
        name: 'Patacones',
        description: "Crispy fried plantain & side of sofrito sauce. Vegan.",
        price: 6.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Starters',
        glutenFree: true,
        vegan: true,
    },
    {
        id: 11,
        name: 'Sweet fried plantain',
        description: "Vegan, gluten free.",
        price: 6.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Starters',
        glutenFree: true,
        vegan: true,
    },
    {
        id: 12,
        name: 'Arepa de Huevo',
        description: "Fried egg filled fritter.",
        price: 5.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Starters',
    },
    {
        id: 13,
        name: 'Chips',
        description: "Vegan, gluten free.",
        price: 4.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Starters',
        glutenFree: true,
        vegan: true,
    },
    {
        id: 14,
        name: 'Pastel de Yuca',
        description: "Rice, egg & beef stuffed cassava.",
        price: 6.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Starters',
        glutenFree: true,
    },
    {
        id: 15,
        name: 'Fried cassava',
        description: "Root vegetable (GF).",
        price: 5.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Starters',
        glutenFree: true,
    },
    {
        id: 16,
        name: 'White rice',
        description: "White rice with a hint of garlic.",
        price: 4.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Starters',
    },
    {
        id: 17,
        name: 'Chicken rice',
        description: "A Traditional Colombian rice dish. Pulled chicken and mixed veg. Comes with sweet fried plantains. (GF).",
        price: 13.5,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Rice Dishes',
        glutenFree: true,
    },
    {
        id: 18,
        name: 'Pork rice (Lechona)',
        description: "A Traditional Colombian rice dish. Slow cooked pork and green peas, with arepa on the side. (GF).",
        price: 13.5,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Rice Dishes',
        glutenFree: true,
    },
    {
        id: 19,
        name: 'Vegan Rice',
        description: "Grilled seasonal veggies and sofrito sauce with a side of sweet fried plantain. (GF).",
        price: 13.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Rice Dishes',
        glutenFree: true,
        popular: true,
    },
    {
        id: 20,
        name: 'Chorizo arepa',
        description: "Grilled corn dough pocked stuffed with Colombian chorizo meat and sofrito sauce.",
        price: 9.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Arepas',
        glutenFree: true,
    },
    {
        id: 21,
        name: 'Chicken arepa (GF) (Halal)',
        description: "Grilled corn dough pocked stuffed with grilled chicken and sofrito sauce.",
        price: 9.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Arepas',
        glutenFree: true,
        halal: true,
    },
    {
        id: 22,
        name: 'Cheese and bacon',
        description: "Grilled corn dough pocked stuffed with cheese and grilled bacon.",
        price: 9.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Arepas',
        glutenFree: true,
    },
    {
        id: 23,
        name: 'Colombian scrambled eggs',
        description: "Grilled corn dough pocked stuffed with scrambled eggs and sofrito.",
        price: 9.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Arepas',
        glutenFree: true,
    },
    {
        id: 24,
        name: 'Pork Arepa',
        description: "Grilled corn dough pocket stuffed with slow cooked pork.",
        price: 9.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Arepas',
        glutenFree: true,
    },
    {
        id: 25,
        name: 'XXL Hot Dog',
        description: "Brioche bun with melted cheese, comes with chips. Choose your toppings.",
        price: 12.5,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Hot Dogs',
        popular: true,
    },
    {
        id: 26,
        name: 'Colombiana (Colombian IRN-BRU) 500 ml',
        price: 3.5,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 27,
        name: 'Postobon Grape Fizzy 500 ml',
        price: 3.5,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 28,
        name: 'Can of tropical Rio',
        price: 1.75,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 29,
        name: 'Can of Coke',
        price: 1.75,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 30,
        name: 'Can of diet Coke',
        price: 1.75,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 31,
        name: 'Hit Juice (lulo)',
        price: 3.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 32,
        name: 'Pony malta',
        price: 3.5,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 33,
        name: 'Can of fruit twist Fanta',
        price: 1.75,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 34,
        name: 'Bottle of Sparkling Water',
        price: 1.5,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 35,
        name: 'Hit Juice (Berries)',
        price: 3.0,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 36,
        name: 'Can of orange Fanta',
        price: 1.75,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 37,
        name: 'Bottle of Water',
        price: 1.5,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    {
        id: 38,
        name: 'Postobon Apple Fizzy 500 ml',
        price: 3.5,
        image: '/images/vegetarian-pasta.jpg',
        category: 'Drinks',
    },
    // Add more dishes as needed
  ];
  
export default dishesData;